### ISSUE TITLE
Add quick-fix for Jakarta Persistence @Entity diagnostic

### ISSUE THREAD

**Issue by lamminade** [eclipse/lsp4jakarta#101]
If a class is annotated with jakarta.persistence.Entity:
1. The entity class must have a public or protected no-arg constructor (the class may have other constructors).
2. The entity class must not be final. No methods or persistent instance variables of the entity class may be final.

Add quick-fixes to this diagnostic to:
- add a public or no-arg constructor if none present
- remove the final keyword from the class, methods, or persistent instances variables if present

See https://jakarta.ee/specifications/persistence/3.0/jakarta-persistence-spec-3.0.html#a18

**Comment by kathrynkodama** [comment]
This issue corresponds to this diagnostic: https://github.com/eclipse/lsp4jakarta/issues/48

Keep in mind that in Java if there is not a constructor specified the compiler automatically creates a default no-arg constructor during execution.

**Comment by kathrynkodama** [comment]
FYI: @MShocrylas @berasogut
