### ISSUE TITLE
Jakarta CDI Produces and Disposes, Observes and ObservesAsync diagnostic

### ISSUE THREAD

**Issue by Jnnnx7** [eclipse/lsp4jakarta#105]
Add a diagnostic to validate that a producer method cannot have a parameter annotated `@Disposes`, a parameter annotated `@Observes`, or a parameter annotated `@ObservesAsync`
(https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#declaring_producer_method)

Notice: we need to check for bean defining annotations first to make sure the managed bean is discovered.

**Comment by Mandiiiiiii** [comment]
I'll look at this one.

**Comment by AlvinTan2000** [comment]
Depends on #212

**Comment by ajm01** [comment]
fixed via #226
