### ISSUE TITLE
Detecting Implicitly Defined Managed Beans

### ISSUE THREAD

**Issue by hanidamlaj** [eclipse/lsp4jakarta#107]
Some of the upcoming CDI features require detecting whether a class is an implicit managed bean or not. To facilitate development of these new features, we should abstract away the logic of detecting a managed bean through good software design principles.

According to the [CDI docs](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#bean_defining_annotations), a bean class with a bean defining annotation is said to be an implicit bean. The following annotations are the set of bean defining annotations:

- `@ApplicationScoped`, `@SessionScoped`, `@ConversationScoped` and `@RequestScoped` annotations,
- all other normal scope types,
- `@Interceptor` and `@Decorator` annotations,
- all stereotype annotations (i.e. annotations annotated with `@Stereotype`),
- and the `@Dependent` scope annotation.

**Comment by kathrynkodama** [comment]
Closed with #109
