### ISSUE TITLE
Quick fix for Jakarta Bean Validation Constraint diagnostics

### ISSUE THREAD

**Issue by lamminade** [eclipse/lsp4jakarta#113]
See: #53, ~~#63~~

> Add diagnostics for these constraints to ensure they are annotated on the supported types.

Quick fix should remove annotations on unsupported types

**Comment by lamminade** [comment]
@kathrynkodama could you verify this is the desired behaviour for the quickfix and assign to me :)

**Comment by kathrynkodama** [comment]
Sounds good to me, thanks @lamminade I would hold off on #63 since this is not yet implemented. Just focus on #53
