### ISSUE TITLE
Quick fix for Jakarta Bean Validation constraints on static fields diagnostic

### ISSUE THREAD

**Issue by lamminade** [eclipse/lsp4jakarta#114]
See #55

> Static fields and static methods are excluded from validation. Add a diagnostic that delivers a warning if a user tries to use a constraint annotation on a static field or method.

Quick fix should suggest removing the constraint annotation on a static field or method

**Comment by lamminade** [comment]
@kathrynkodama could you verify this is the desired behaviour for the quickfix and assign to me :)

**Comment by kathrynkodama** [comment]
@lamminade looks good to me, thank you
