### ISSUE TITLE
Diagnostic and Quick Fix for Root Resource Class Constructors

### ISSUE THREAD

**Issue by MShocrylas** [eclipse/lsp4jakarta#116]
From [3.1.2](https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html#resource_class_constructor):

> Root resource classes are instantiated by the JAX-RS runtime and MUST have a public constructor for which the JAX-RS runtime can provide all parameter values. Note that a zero argument constructor is permissible under this rule.

A root resource class is: A resource class annotated with @​Path.

Create a warning if a root resource class with a least 1 defined constructor has no public constructor.

Quick fixes: 
- Create empty public constructor
- Make non public constructor public (optional)

See similar: #124

**Comment by berasogut** [comment]
I tested and root resource classes still work when there are no constructors defined since Java's default constructor is public. I think we should create a warning when there is at least 1 constructor defined and none of them are public but we can keep the quick fixes the same.

**Comment by MShocrylas** [comment]
Yeah that makes sense, I'll clarify the issue with that.
