### ISSUE TITLE
Diagnostic and Quick Fix for Resource Method Entity Parameters 

### ISSUE THREAD

**Issue by MShocrylas** [eclipse/lsp4jakarta#117]
From [3.3.2.1](https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html#entity_parameters):
> Resource methods MUST have at most one entity parameter.

An entity parameter is: A resource method parameter not annotated with @FormParam or any of the annotations listed in [Fields and Bean Properties](https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html#resource_field).

Create a warning if there is more than one non-annotated parameter to a resource method .

Quick Fix:

- Remove all except the first entity parameter from a method

**Comment by berasogut** [comment]
@kathrynkodama can you assign this one to me? Thanks!

**Comment by kathrynkodama** [comment]
Closed with #131, follow up quick-fix issue: #132
