### ISSUE TITLE
Diagnostic for Root Resource Class with Multiple Public Constructors of Different Length

### ISSUE THREAD

**Issue by MShocrylas** [eclipse/lsp4jakarta#118]
From [3.1.2](https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html#resource_class_constructor):
> If more than one public constructor is suitable then an implementation MUST use the one with the most parameters.

A root resource class is: A resource class annotated with @​Path.

If a root resource class has multiple public constructors with different numbers of parameters, create a warning that the ones with less parameters are not used.

See related #119

**Comment by kathrynkodama** [comment]
I think we can display a warning for this issue, but we may not need a quick-fix for it as developers may want to keep the other constructors

**Comment by kathrynkodama** [comment]
Perhaps this could be tagged `DiagnosticSeverity.Warning` as opposed to Error

**Comment by MShocrylas** [comment]
Removed the quick fix
