### ISSUE TITLE
Diagnostic for Root Resource Class with Multiple Public Constructors with Equal Number of Parameters

### ISSUE THREAD

**Issue by MShocrylas** [eclipse/lsp4jakarta#119]
From [3.1.2](https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html#resource_class_constructor):
> Choosing amongst suitable constructors with the same number of parameters is implementation specific, implementations SHOULD generate a warning about such ambiguity.

A root resource class is: A resource class annotated with @​Path.

If a root resource class has multiple public constructors with the same number of parameters, create a warning that the chosen constructor is implementation specific and may be ambiguous.

See related #118

**Comment by kathrynkodama** [comment]
Again we may not need a quick-fix for this issue

**Comment by MShocrylas** [comment]
Removed quick fix from here as well
