### ISSUE TITLE
Add quick-fix for Jakarta CDI Produces, Inject, Disposes, Observes/ObservesAsync diagnostics

### ISSUE THREAD

**Issue by Jnnnx7** [eclipse/lsp4jakarta#134]
- [x] **A bean constructor or an initializer method annotated with `@Inject` cannot have a parameter annotated `@Disposes`, `@Observes`, or `@ObservesAsync`**
See the issue for corresponding diagnostic here: https://github.com/eclipse/lsp4jakarta/issues/104

Add two quick-fixes for this diagnostic:
1. Remove the `@Inject` annotation
2. Remove the conflicted annotations (`@Disposes`, `@Observes`, and/or `@ObservesAsync`)<br/><br/>

- [x] **A producer method cannot have a parameter annotated `@Disposes`, `@Observes`, or `@ObservesAsync`**
See the issue for corresponding diagnostic here: https://github.com/eclipse/lsp4jakarta/issues/105

Add two quick-fixes for this diagnostic:
1. Remove the `@Produces` annotation
2. Remove the conflicted annotations (`@Disposes`, `@Observes`, and/or `@ObservesAsync`)<br/><br/>

- [x] **A method cannot have more than one parameter annotated `@Disposes`**
See the issue for corresponding diagnostic here: https://github.com/eclipse/lsp4jakarta/issues/106

Add a quick-fix to remove the extra `@Disposes` annotations<br/><br/>

- [x] **A disposer method cannot have a parameter annotated @Observes or a parameter annotated @ObservesAsync**
See the issue for corresponding diagnostic here: https://github.com/eclipse/lsp4jakarta/issues/106

Add two quick-fixes for this diagnostic:
1. Remove the `@Disposes` annotation
2. Remove the conflicted annotations (`@Observes`, and/or `@ObservesAsync`)

**Comment by ajm01** [comment]
fixed in #511
