### ISSUE TITLE
Distinguish between jakarta.ws.rs.Produces and jakarta.enterprise.inject.Produces

### ISSUE THREAD

**Issue by Mandiiiiiii** [eclipse/lsp4jakarta#139]
Diagnostics and quick fixes for `@Produces` in CDI should only work with `@Produces` in `jakarta.enterprise.inject` and ignore `@Produces` in `jakarta.ws.rs`

Related PR:
- https://github.com/eclipse/lsp4jakarta/pull/112
- https://github.com/eclipse/lsp4jakarta/pull/125

**Comment by kathrynkodama** [comment]
Closing as it is a duplicate of #140
