### ISSUE TITLE
Add support for jakarta.annotation.PostConstruct

### ISSUE THREAD

**Issue by tiganov** [eclipse/lsp4jakarta#156]
[Spec](https://jakarta.ee/specifications/annotations/2.0/annotations-spec-2.0.html#jakarta-annotation-postconstruct)

- [ ] The annotated method must not have any parameters.
- [ ] The annotated method must be `void`.
- [ ] The annotated method must not throw checked exceptions

Quickfixes
- [ ] Remove parameters from method
- [ ] Change return type to void
- [ ] Remove checked exceptions from signature

Related to #152.

**Comment by tiganov** [comment]
Initial implementation: [commit on my fork](https://github.com/tiganov/lsp4jakarta/commit/4d9aeaba1ec9ba3a16e50e0c0e0c2e9be8ab211e).

**Comment by shaunak** [comment]
I'll work on this

**Comment by Future-Genius** [comment]
I am working on quickfix of this issue

**Comment by tiganov** [comment]
Closing: this issue has been split into smaller issues.
