### ISSUE TITLE
Add support for jakarta.annotation.Resource

### ISSUE THREAD

**Issue by tiganov** [eclipse/lsp4jakarta#157]
[Spec](https://jakarta.ee/specifications/annotations/2.0/annotations-spec-2.0.html#jakarta-annotation-resource)

- [ ] The `name` attribute must be specified when the annotation is used on a class.
- [ ] The `type` attribute must be specified when the annotation is used on a class.

If the annotation is used on a method and the method starts with "set," the return type must be void or, if the `type` attribute is set, must "be compatible" with it. We likely cannot soundly check this without a type hierarchy. Comparing the `type` attribute with the `IMethod` return type is also not reliable because only the latter uses proper type signature format.

Quickfixes

- [ ] Add missing name attribute
- [ ] Add missing type attribute

Related to #152.

**Comment by tiganov** [comment]
Initial implementation: [commit on my fork](https://github.com/tiganov/lsp4jakarta/commit/4d9aeaba1ec9ba3a16e50e0c0e0c2e9be8ab211e).

**Comment by shaunak** [comment]
I'll work on this

**Comment by Future-Genius** [comment]
I'm working on quickfix

**Comment by tiganov** [comment]
Closing: this issue has been split into smaller issues.
