### ISSUE TITLE
Depedency Injection: Diagnostic for handling more than one `@Qualifier`

### ISSUE THREAD

**Issue by AlvinTan2000** [eclipse/lsp4jakarta#165]
[Spec](https://jakarta.ee/specifications/dependency-injection/2.0/apidocs/jakarta/inject/inject)

Unchecked Errors:
- [ ] When more than one `@Qualifier` annotation is provided

Potential Solution:
- [ ] Remove the last `@Qualifier`

Related to #153

**Comment by kathrynkodama** [comment]
Is this diagnostic to warn users when they have a field/method with `@Inject` and more than one qualifier annotation? 

According to https://jakarta.ee/specifications/dependency-injection/2.0/apidocs/jakarta/inject/inject:
> A qualifier may annotate an injectable field or parameter and, combined with the type, identify the implementation to inject. Qualifiers are optional, and when used with @Inject in injector-independent classes, no more than one qualifier should annotate a single field or parameter. The qualifiers are bold in the following example:
> 
>    public class Car {
>      @Inject private @Leather Provider<Seat> seatProvider;
> 
>      @Inject void install(@Tinted Windshield windshield,
>          @Big Trunk trunk) { ... }
>    }
> If one injectable method overrides another, the overriding method's parameters do not automatically inherit qualifiers from the overridden method's parameters.
> 

In the example above, how would we determine that `@Leather` and `@Tinted` are qualifier annotations if they are in separate classes. We may not have knowledge of those classes.

Also see https://jakarta.ee/specifications/dependency-injection/2.0/apidocs/jakarta/inject/qualifier

**Comment by AlvinTan2000** [comment]
> Is this diagnostic to warn users 
The diagnostic should show an error since it would not compile properly when annotated

> when they have a field/method with @Inject and more than one qualifier annotation?
Yes, that is correct.

> In the example above, how would we determine that @Leather and @Tinted are qualifier annotations if they are in separate classes. We may not have knowledge of those classes.
I guess that does pose a problem. 

Maybe if the annotations appear in front of a type or alongside with an `@Inject`, we can infer it is a `@Qualifier`?  Or we could internally keep track of the declared `@Qualifiers` (not sure whether that is possible).

**Comment by AlvinTan2000** [comment]
According to [spec](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#declaring_bean_qualifiersl)
> Any bean may declare multiple qualifier types

Closing this issue until more detailed error can be specified.
