### ISSUE TITLE
Add support for handling more than one @Scope

### ISSUE THREAD

**Issue by AlvinTan2000** [eclipse/lsp4jakarta#166]
[Spec](https://jakarta.ee/specifications/dependency-injection/2.0/apidocs/jakarta/inject/inject)

Unchecked Errors:
- [ ]  When more than one `@Scope` annotation is provided

Potential Solution:
- [ ] Remove the last `@Scope`

Related to #153

**Comment by kathrynkodama** [comment]
Is this a duplicate of #103?

**Comment by AlvinTan2000** [comment]
Yes it is a duplicate, did not realize. 

Closing it.
