### ISSUE TITLE
Depedency Injection: Diagnostic  for `final`, `abstract`, `static` and generic `@Inject` methods

### ISSUE THREAD

**Issue by AlvinTan2000** [eclipse/lsp4jakarta#168]
[Depedency Injection Spec](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#initializer_methods)

> An initializer method is a default-access, public, protected or private, non-abstract, non-static, non-generic method of a bean class or of any other classes supporting injection.

Diagnostics
- Identify `@Inject` methods 
- If method is `final`, `abstract`, `static` and generic, deliver diagnostic error

Quick Fix:
- Remove the modifiers
- Remove the annotation

Related to #153

**Comment by kathrynkodama** [comment]
Similar to #167, clarify the spec and if this is for `@Inject`

**Comment by AlvinTan2000** [comment]
I have edited the title to now reflect having to provide diagnostics for `static` and generic methods based on this [spec](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#initializer_methods)

> An initializer method is a default-access, public, protected or private, non-abstract, non-static, non-generic method of a bean class or of any other classes supporting injection.
