### ISSUE TITLE
Update BUILDING.md with relevant changes

### ISSUE THREAD

**Issue by shaunak** [eclipse/lsp4jakarta#169]
Proposed Changes:

- add a reminder on step 2 to ensure script is being run with JavaSE-11 by checking $JAVA_HOME

**Comment by kathrynkodama** [comment]
JAVA_HOME is referenced in the common errors section of the building document: https://github.com/eclipse/lsp4jakarta/blob/main/docs/BUILDING.md#common-errors

Should this be more obvious or included in the pre-requisite steps?
