### ISSUE TITLE
Add quickfixes for jakarta.annotation.PostConstruct

### ISSUE THREAD

**Issue by tiganov** [eclipse/lsp4jakarta#183]
Add quickfixes for diagnostics (#181).

- [x] Remove parameters from method (completed with #203)
- [ ] Change return type to void
~~- [ ] Remove checked exceptions from signature~~ This will be completed as part of #193 

Based on #156.

**Comment by Future-Genius** [comment]
i work on this

**Comment by kathrynkodama** [comment]
Closed with [Quickfix for PreDestroy and Resource #203](https://github.com/eclipse/lsp4jakarta/pull/203)
