### ISSUE TITLE
Dependency Injection: Diagnostics for bean class of generic or parameterized type

### ISSUE THREAD

**Issue by AlvinTan2000** [eclipse/lsp4jakarta#210]
[Managed Beans](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#managed_beans)

> If the managed bean class is a generic type, it must have scope @Dependent. If a managed bean with a parameterized bean class declares any scope other than @Dependent, the container automatically detects the problem and treats it as a definition error.

## Diagnostics
1. Check if class is a [managed bean](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#what_classes_are_beans)
2. Check if managed bean is of generic/parameterized type
3. Check if dependency class is annotated with `@Dependent` or has no other scope specified
4. If not, deliver an error at the class declaration

## Quickfixes
- Suggest removing scope

## Example
```java
@ApplicationScoped
// Error here due to the generic type
public class Greeting<T>{
	public String greet(String name) {
        return "GreetingA, " + name;
    }
}
```

```
[INFO] [ERROR   ] CWWKZ0004E: An exception occurred while starting the application demo-servlet. The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DefinitionException: WELD-000071: Managed bean with a parameterized bean class must be @Dependent: class io.openliberty.sample.jakarta.di.error.generic.Greeting
```

Related to #153

**Comment by AlvinTan2000** [comment]
I will work on this

**Comment by kathrynkodama** [comment]
> 1. Identify `@Inject` field/method/constructor
> 2. Check if dependency class is a generic/parameterized type
> 3. Check if dependency class is annotated with `@Dependent` or has no other scope specified
> 4. If so, deliver an error at the class declaration

Is step (1) really needed to check for this diagnostic? If not let's remove it

**Comment by AlvinTan2000** [comment]
I have updated the diagnostics accordingly.
