### ISSUE TITLE
Jsonb JsonbTransient on class field diagnostic

### ISSUE THREAD

**Issue by adit333** [eclipse/lsp4jakarta#241]
#### Description:
@JsonbTransient is mutually exclusive with all other JSON Binding defined annotations. That is, when this annotation is present on a class field, then there should be no other annotations on that class field.

#### Specification:
Acceptable:
```java
@JsonbTransient
String name;
```

Error:
```java
@JsonbTransient
@JsonbProperty("name")
String name;
```
[JsonbTransient Annotation](https://jakarta.ee/specifications/jsonb/2.0/apidocs/jakarta/json/bind/annotation/jsonbtransient)

Specifically, when `@JsonbTransient` annotation is present on a field, the following annotations should not be there on the same field:
```
@JsonbAnnotation
@JsonbCreator
@JsonbDateFormat
@JsonbNillable
@JsonbNumberFormat
@JsonbProperty
@JsonbPropertyOrder
@JsonbTypeAdapter
@JsonbTypeDeserializer
@JsonbTypeSerializer
@JsonbVisibility
```

#### Type of language feature proposed:
_Select all that apply_
- [x] diagnostic
- [ ] quick-fix
- [ ] snippet
- [ ] other, please specify:

**Comment by kathrynkodama** [comment]
Thanks @adit333, from the spec:
_If a class field is annotated with @JsonbTransient, exception is thrown when this field, getter or setter is annotated with other JSON Binding annotations._

Can you please clarify/list what the other JSON Binding annotations the diagnostic would check for?

**Comment by adit333** [comment]
Yes, it can be closed
