### ISSUE TITLE
WebSocket: PathParam URI Mismatch Diagnostic

### ISSUE THREAD

**Issue by TheAvi123** [eclipse/lsp4jakarta#245]
#### Description:

A warning should be presented to the developer when a PathParam annotation is used for a lifecycle method that has a value which does not correspond to any of the variable segments of the ServerEndpoint URI. In such a case, the method parameter associated with the PathParam annotation will always be null and may have unintended effects on the application logic.

#### Specification:

If the value attribute of this annotation matches the variable name of an element of the URI-template used in the ServerEndpoint annotation that annotates this annotated endpoint, then the implementation must associate the value of the parameter it annotates with the value of the path segment of the request URI to which the calling WebSocket frame is connected when the method is called [WSC-4.3-3]. Otherwise, the value of the String parameter annotated by this annotation must be set to null by the implementation.

[Link to @PathParam Specification](https://jakarta.ee/specifications/websocket/2.0/websocket-spec-2.0.html#pathparam)

#### Type of language feature proposed:
_Select all that apply_
- [x] diagnostic
- [ ] quick-fix
- [ ] snippet
- [ ] other, please specify:

**Comment by TheAvi123** [comment]
@kathrynkodama I'm working on this issue!

**Comment by kathrynkodama** [comment]
Closed with #266
