### ISSUE TITLE
Transaction: Code snippet for begin() and commit() methods

### ISSUE THREAD

**Issue by Jellal-HT** [eclipse/lsp4jakarta#250]
#### Description:
Providing code snippet for `begin()` and `commit()` methods of `UserTransaction` and `TransactionManager` interfaces

#### Specification:
For UserTransaction and TransactionManager interfaces, they all have a `begin()` method to start a transaction, and need to have a `commit()` method to complete the transaction. Therefore, a code snippet can be provided for `begin()` and `commit()` method if the developer want to define a transaction.

#### Example:
If developer types:
```
trs.begin();
```
The following code snippet will be provided:
```
// start of transaction
trs.begin();
/**
* 
* content for transaction:
*
**/
// end of transaction
trs.commit();
```

[Transaction Specification](https://jakarta.ee/specifications/transactions/2.0/jakarta-transactions-spec-2.0.html#jakarta-transactions-specification-version-2-0)
[Transaction API](https://jakarta.ee/specifications/transactions/2.0/apidocs/)

#### Type of language feature proposed:
_Select all that apply_
- [ ] diagnostic
- [ ] quick-fix
- [x] snippet

- [ ] other, please specify:

**Comment by kathrynkodama** [comment]
@Jellal-HT @sullan-kang can you please add a link to the specification?
