### ISSUE TITLE
Transaction: Code snippet for annotation @Transactional

### ISSUE THREAD

**Issue by Jellal-HT** [eclipse/lsp4jakarta#251]
#### Description:
Providing code snippet for `@Transactional` when using two optional elements `rollbackOn` and `dontRollbackOn`

#### Specification:
A code snippet can be provided for developer, if developer types:
```
@Transactional()
```
The code snippet will be:
```
@Transactional(
        rollbackOn={checkedException.class,……},
        dontRollbackOn={uncheckedException.class,……})
```
In this code snippet, the common checkedException classes(`SQLException.class`, `IOException.class`) will be provided as parameters for the `rollbackOn` element and the common uncheckedException classes(`IllegalStateException.class`) will be provided as parameters for `dontRollbackOn` element, as the default settings for `@Transactional` is that the transaction will marked for rollback for all runtimeException and not result in rollback for all checkedException. 

[Transaction Specification](https://jakarta.ee/specifications/transactions/2.0/jakarta-transactions-spec-2.0.html#:~:text=By%20default%20checked,dontRollbackOn%20takes%20precedence)

#### Type of language feature proposed:
_Select all that apply_
- [ ] diagnostic
- [ ] quick-fix
- [x] snippet
- [ ] other, please specify:

**Comment by kathrynkodama** [comment]
@Jellal-HT can you please provide a link to the spec detailing how `@Transactional` is used
