### ISSUE TITLE
Quick fix for Jsonb Transient Accessor Diagnostics

### ISSUE THREAD

**Issue by adit333** [eclipse/lsp4jakarta#292]
#### Description:
This is a follow up for issue #268 

If the diagnostic is that there are non mutually exclusive annotations on the accessor, then add quick fix to remove the either the @JsonbTransient annotation or other Jsonb annotations on the accessors. As an example:
```java
@JsonbProperty("name")
@JsonbAnnotation
@JsonbTransient
public String getName() {
    return name;
}
```
In this case the quick fix should be to either remove `@JsonbProperty("name"), @JsonbAnnotation` or remove `@JsonbTransient`.

If the diagnostics is that there is a conflict on the accessor and the field, then provide a quick fix to remove either the annotation on the field or the accessor. Example of a conflict:
```java
@JsonbProperty("name")
private String name;

@JsonbTransient
public String getName() {
    return name;
}
```
In this case the quick fix should be to either remove `@JsonbProperty("name")` or remove `@JsonbTransient`.

#### Type of language feature proposed:
_Select all that apply_
- [ ] diagnostic
- [x] quick-fix
- [ ] snippet
- [ ] other, please specify:

**Comment by adit333** [comment]
I'd like to pick up this issue.

**Comment by ajm01** [comment]
addressed by the merge of https://github.com/eclipse/lsp4jakarta/pull/280
