### ISSUE TITLE
Update snippets with more relevant names, prefixes and descriptions for Jakarta EE 9+

### ISSUE THREAD

**Issue by kathrynkodama** [eclipse/lsp4jakarta#336]
The Jakarta RESTful Web Services snippets still refer to "JAX-RS" in the description: https://github.com/eclipse/lsp4jakarta/blob/7fb1fe4fdfac031819f426240b6227b06ab712d1/jakarta.ls/src/main/resources/jax-rs.json#L2-L25
Update to use more relevant names, prefixes and descriptions for Jakarta EE 9+

Also consider if any of the other snippets should be updated in the same way:
https://github.com/eclipse/lsp4jakarta/tree/main/jakarta.ls/src/main/resources

**Comment by yeekangc** [comment]
Should consider updates to the prefixes where appropriate too.
