### ISSUE TITLE
Snippets invoked via type-ahead are not indented properly

### ISSUE THREAD

**Issue by awisniew90** [eclipse/lsp4jakarta#349]
When using snippets (like jaxrc), the loaded snippet is not indented properly and still shows the "jaxrc" that the user typed:

```
jaxrcpackage packagename;
					
					import jakarta.ws.rs.GET;
					import jakarta.ws.rs.Path;
					import jakarta.ws.rs.Produces;
					import jakarta.ws.rs.core.MediaType;
					
					@Path("/path")
					public class classname {
					
						@GET
						@Produces(MediaType.TEXT_PLAIN)
						public String methodname() {
							return "hello";
						}
					}
```

**Comment by awisniew90** [comment]
This was on Mac. Eclipse 2022-09. Java 17.

**Comment by yeekangc** [comment]
Common issue reported by multiple users that hopefully can be addressed ASAP to improve usability.

**Comment by bensonnw** [comment]
Is your Java file empty before using the snippet? It seems working for me, but I am using Eclipse on Windows. 
![image](https://user-images.githubusercontent.com/58234271/198076886-40d2ed3c-9209-4314-b455-6387b6f5946c.png)

**Comment by awisniew90** [comment]
@bensonnw  - Java file is empty.  If it's any help, this only seems to happen if I start typing the snippet I want (e.g. jaxrc). If I just invoke type-ahead and scroll/select "jaxrc" the indentation seems fine. This issue may overlap with #348

**Comment by bensonnw** [comment]
@mattbsox , please give it a try once you have time. thx

**Comment by ajm01** [comment]
i recreated it on Windows Eclipse 09-2022, empty file started typing after hitting Ctrl-Space, not sorting occurred:
![image](https://user-images.githubusercontent.com/31104727/198144642-f22c5e4f-1403-47cc-9cc9-700a447cfd6f.png)

Found 'servletwebfilter' in the generated list:
![image](https://user-images.githubusercontent.com/31104727/198144830-f9daa68f-5311-4620-913e-726706861513.png)

Chose it and same issue - snippet code inserted directly after the type ahead string i had previously entered:

**Comment by TrevCraw** [comment]
Not an issue with IntelliJ. Need to test with VS Code. @kathrynkodama @dshimo

**Comment by TrevCraw** [comment]
New issue opened to address user input being left in once a snippet is selected: https://github.com/eclipse/lsp4jakarta/issues/353
This issue will address the indentation problem.

**Comment by dshimo** [comment]
Correcting myself from a week ago where this does occur in VS Code
![image](https://user-images.githubusercontent.com/8934136/200615945-bd31a728-1c63-486c-864f-39d40fb3e7c9.png)
The bug occurs as @bensonnw and @awisniew90 describe

**Comment by bensonnw** [comment]
fixed
