### ISSUE TITLE
Document what is supported in which release of LSP4Jakarta

### ISSUE THREAD

**Issue by yeekangc** [eclipse/lsp4jakarta#350]
Document or at least summarise what capabilities (coding assistance) are supported in which release of LSP4Jakarta.

e.g., translate what is captured in https://github.com/eclipse/lsp4jakarta/issues/16 to an end-user (developer) consumable information mapping to the corresponding release(s) of the language server.

**Comment by TrevCraw** [comment]
@yeekangc Is this necessary to document before d-cut? If so, work on this will have an impact on d-cut development work.

**Comment by yeekangc** [comment]
I believe we should document what is relevant as best we can for each release we put out there.

Yes, understand that we are working through various development items.  As we get to more established development schedule and release cadence for the project, documentation or description for what is available in each release (0.x or not) should be part of the release cycle.

**Comment by kathrynkodama** [comment]
Documentation for snippets was added with #365

**Comment by kathrynkodama** [comment]
Documentation for diagnostics & quick-fixes are still outstanding, and should be added to the README: https://github.com/eclipse/lsp4jakarta#jakarta-ee-api-language-features

**Comment by kathrynkodama** [comment]
Closed with https://github.com/eclipse/lsp4jakarta/pull/417
