### ISSUE TITLE
Should not insert the whole proposed class code at the current cursor location

### ISSUE THREAD

**Issue by gkwan-ibm** [eclipse/lsp4jakarta#379]
For the `presist_entity`, `rest_class`, or other proposals,  they should not simply insert the whole proposed class code to the file. It causes many complication errors. It should either replace the whole file or only propose when the file is empty. Similar as the `new_class` proposal in an empty file, press Ctrl+Space twice or three times to get following:

<img width="671" alt="Screen Shot 2022-11-21 at 2 53 19 PM" src="https://user-images.githubusercontent.com/29576299/203402931-a0449de1-7f20-4834-a3de-963ef4d2220e.png">

**Comment by kathrynkodama** [comment]
We should not delete the entire class for the user, but we could consider making the snippets more context-aware (second suggestion only proposing when the file is empty)

**Comment by kathrynkodama** [comment]
See https://github.com/eclipse/lsp4mp/issues/322

**Comment by TrevCraw** [comment]
The goal of this issue is to make the snippets more context aware based on changes made in https://github.com/eclipse/lsp4mp/pull/338

**Comment by turkeylurkey** [comment]
Creating a new message to obtain the context of the cursor. This will be used to filter the snippets. For the case above we have an empty file context. Other contexts will filter certain snippets out. 

Currently we have implemented the message part and we're working on the filtering part.

**Comment by rumanaHaque** [comment]
Using the latest VSCode driver that @TrevCraw uploaded on May 25th, validated that this problem does not occur any more.

Here's a screenshot of auto-complete for import jakarta.

![image](https://github.com/eclipse/lsp4jakarta/assets/31224827/6724cd17-1318-4599-9580-1871f7045852)
