### ISSUE TITLE
persist_context_extended_unsync generates {2:em} that is strange

### ISSUE THREAD

**Issue by gkwan-ibm** [eclipse/lsp4jakarta#381]
The `persist_context_extended_unsync` proprosal generates `{2:em}` that is strange

<img width="677" alt="Screen Shot 2022-11-21 at 2 45 32 PM" src="https://user-images.githubusercontent.com/29576299/203410733-9af2a8a4-e0b3-46c1-9454-31d819ecad2b.png">

**Comment by kathrynkodama** [comment]
See https://github.com/eclipse/lsp4mp/issues/325

**Comment by bensonnw** [comment]
Fixed
