### ISSUE TITLE
Use of commons.lang3 results in unsigned content warning during Eclipse IDE install

### ISSUE THREAD

**Issue by scottkurz** [eclipse/lsp4jakarta#395]
When installing https://marketplace.eclipse.org/content/liberty-tools into the v4.25 (22-09) Eclipse for Java Developers, we get an unsigned content warning.

It seems to come from our dependency on `org.eclipse.lsp4jakarta.jdt.core` and its require-bundle of `org.apache.commons.lang3`.

I wonder, instead of solving this if it could even be easier just to remove the dependency.  There's only a trivially-small usage of this library (see grep below):

> * org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/TextEditConverter.java: import org.apache.commons.lang3.StringUtils;
> * org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/jax_rs/ResourceMethodDiagnosticsCollector.java: import org.apache.commons.lang3.ArrayUtils;

**Comment by scottkurz** [comment]
I installed the v4.25 Eclipse for Enterprise Java package and I see this plugin is coming from:
> 	Eclipse Orbit	Apache Commons Lang	3.1.0.v201403281430	org.apache.commons.lang3 

This is the same version I saw the complaint about when installing from the Eclipse for Java package and the Installation Details -> Installed Software shows it's unsigned here in my Enterprise Java install as well.

**Comment by mezarin** [comment]
Closing this issue because when installing LTE (23.0.12) on Eclipse IDE for Java Developers  2023-09, there are appears to be unsigned content, but not what was reported or anything associated with this  project.

<img width="813" alt="image" src="https://github.com/eclipse/lsp4jakarta/assets/8353153/9569cfe1-6890-4e3f-8e39-895268dc1bb4">
