### ISSUE TITLE
Implement dynamic templating in completionSnippets

### ISSUE THREAD

**Issue by AnkushSharma2698** [eclipse/lsp4jakarta#43]
Certain key variables should resolve automatically in snippets.
Example:
```
${package_name}
```
Should resolve automatically based on the context to
```
package com.example.system;
```

I just did some testing, and the proposed method doesnt actually work in eclipse rn. I tried messing around with templates in eclipse and that does fill in snippets with variables as we want but for whatever reason that is not extending to our current completion framework. So for now I would say we should keep snippets like this. In order to accomodate the change in this request I think i would have to restructure completionProposalComputer a bit and I am not sure about what is needed for that yet

**Comment by bensonnw** [comment]
What `dynamic templating` are we looking for here? Current `completionSnippets` code is in LS side, there is no JDT information available, we need APIs to communicate with client. 
There are many variables defined in JSON files, `${1:packagename}`, `${2:path}`, `${3:className}`, `${4:methodname}` etc. we only need to resolve package and class names?
