### ISSUE TITLE
Error diagnostic returned for non-public resource method on interface, but interface method should be treated as public 

### ISSUE THREAD

**Issue by scottkurz** [eclipse/lsp4jakarta#447]
#### Description:
Using LSP4Jakarta v0.1.0, if I follow the [Open Liberty MicroProfile Rest Client guide](https://openliberty.io/guides/microprofile-rest-client.html) we get an error diagnostic [here](https://github.com/OpenLiberty/guide-microprofile-rest-client/blob/00b327f4387cf844be45f35c0595355b0574cdec/finish/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java#L45) on line: 

>  Properties getProperties() throws UnknownUriException, ProcessingException;

with message "Only public methods may be exposed as resource methods".   

Since SystemClient is an interface, however, this seems like an incorrect way to check.   This should be treated as a public method for this check.

#### Type of language feature proposed:
_Select all that apply_
- [X] diagnostic

**Comment by mezarin** [comment]
Fixed by PR #490
