### ISSUE TITLE
Class and package names not completed

### ISSUE THREAD

**Issue by TrevCraw** [eclipse/lsp4jakarta#456]
This appears to be regression from changes in #452 or #453 
Screenshot below is from VS Code. Need to test in Eclipse.

![package-and-class-not-filled-in](https://github.com/eclipse/lsp4jakarta/assets/5885743/ef747ae5-add2-4973-90dc-93102450e959)

**Comment by turkeylurkey** [comment]
Confirmed in IntelliJ using development driver.

**Comment by scottkurz** [comment]
Confirming the problem exists in Liberty Tools Eclipse (we haven't released Liberty Tools Eclipse v0.9.1, but are building it now from https://github.com/OpenLiberty/liberty-tools-eclipse/commit/fe2eabb19be7484f11fa4d5ae3b2284b75130649).
