### ISSUE TITLE
Would it be better to not use default methods in JakartaLanguageClientAPI to force clients to pick up changes?

### ISSUE THREAD

**Issue by scottkurz** [eclipse/lsp4jakarta#457]
So if we look at the recent changes: 

https://github.com/eclipse/lsp4jakarta/pull/452
https://github.com/eclipse/lsp4jakarta/pull/453

from the perspective of Liberty Tools Eclipse, the changes completely broke the existing ability to use snippets as completion proposals.

The fix was as simple as adding the new method to our JakartaLanguageClientAPI impl in Liberty Tools Eclipse:
https://github.com/OpenLiberty/liberty-tools-eclipse/pull/387/files

If it weren't for the use of default methods in: https://github.com/eclipse/lsp4jakarta/blob/main/jakarta.ls/src/main/java/org/eclipse/lsp4jakarta/api/JakartaLanguageClientAPI.java
this would've been easily detected as a compile-time error... instead we had to go through a debug process.

Is it really helpful to try to support older "clients" with newer levels of LSP4Jakarta in a case like this by adding the default method?    Or is it better to assume a client depends on a specific version of LSP4Jakarta, and to communicate that the new client needs to implement this interface?

**Comment by angelozerr** [comment]
+1

We did that for microprofile ls and qute ls 
See https://github.com/eclipse/lsp4mp/issues/398

**Comment by mezarin** [comment]
Closing this issue as it has already been resolved by #495
