### ISSUE TITLE
LSP4Jakarta & LSP4MP field and method snippets show up before top level classes

### ISSUE THREAD

**Issue by TrevCraw** [eclipse/lsp4jakarta#464]
#### Description:

- This behaviour is seen in VS Code and Eclipse
- LSP4Jakarta field and method snippets also show up after an @ sign as well, (LSP4MP snippets do not)
- LSP4Jakarta and LSP4MP snippets show up amongst import statements in various contexts. If snippets are disabled before top level classes, the import contexts would not need to be considered, at least while there are no valid snippets for “before a top level class”.
- It is expected that field and method snippets would not be suggested before a top level class.

#### Type of language feature proposed:
_Select all that apply_
- [ ] diagnostic
- [ ] quick-fix
- [x] snippet
- [ ] other, please specify:

**Comment by turkeylurkey** [comment]
Similar: https://github.com/eclipse/lsp4mp/issues/402
