### ISSUE TITLE
Fix release build to push all jakarta.jdt artifacts to repo.eclipse.org

### ISSUE THREAD

**Issue by mattbsox** [eclipse/lsp4jakarta#473]
#### Description:
The release build currently only pushes the jakarta.jdt.parent pom.xml file to repo.eclipse.org.

The build needs to be updated to include all generated subproject artifacts in the jakarta.jdt project.

**Comment by turkeylurkey** [comment]
Fixed by https://github.com/eclipse/lsp4jakarta/pull/491
