### ISSUE TITLE
Filter diagnostics based on classpath/imports

### ISSUE THREAD

**Issue by kathrynkodama** [eclipse/lsp4jakarta#54]
Possibly can use the `JavaModelUtil.getClasspathEntry` method

**Comment by kathrynkodama** [comment]
Possible design decision around if we should show diagnostics if the API is not on the classpath, but it is clear they are intending to use that API given the import statements. We should compare to LSP4MP and JDT LS

**Comment by bensonnw** [comment]
- [ ] Validate JakartaEE annotations
- [ ] `@Generated` annotation is missing support for method parameters

**Comment by kathrynkodama** [comment]
https://github.com/eclipse/lsp4jakarta/issues/159 looks related to  "Check interface hierarchy for Java class annotated by @WebListener" also see the issues tagged https://github.com/eclipse/lsp4jakarta/labels/project-info-needed
