### ISSUE TITLE
Jakarata Bean Validation Snippets for built-in constraints

### ISSUE THREAD

**Issue by rezaakv** [eclipse/lsp4jakarta#64]
Make useful snippets similar to @Email snippet #52 for Bean Validation constraints. There could be snippets for: Digits, DecimalMax, DecimalMin, PastOrPresent, FutureOrPresent, Past, Future, Min, Max, NegativeOrZero, PostiveOrZero, Negative, Positive, NotBlank, Pattern, NotEmpty, and Size annotations.

**Comment by kathrynkodama** [comment]
Closing as these snippets are not needed
