### ISSUE TITLE
Add quick-fix for Jakarta Persistence MapKey diagnostic

### ISSUE THREAD

**Issue by kathrynkodama** [eclipse/lsp4jakarta#75]
The `@MapKeyClass` and `@MapKey` annotations cannot be used on the same field or property. See the corresponding diagnostic here: https://github.com/eclipse/lsp4jakarta/blob/master/jakarta-eclipse/src/org/jakarta/jdt/persistence/PersistenceMapKeyDiagnosticsCollector.java#L75-L109

Add two quick-fixes for this diagnostic: 
1) Remove the `@MapKeyClass` annotation
2) Remove the `@MapKey` annotation

This will involve creating a new Proposal class called "DeleteAnnotationProposal" modelled after [ModifyAnnotationProposal](https://github.com/eclipse/lsp4jakarta/blob/master/jakarta-eclipse/src/org/jakarta/codeAction/proposal/ModifyAnnotationProposal.java).  
See an example quick-fix here: https://github.com/eclipse/lsp4jakarta/pull/73/files

**Comment by Mandiiiiiii** [comment]
Could I try this one?
