### ISSUE TITLE
Add quick-fix for Jakarta Persistence MapKeyJoinColumn diagnostic

### ISSUE THREAD

**Issue by kathrynkodama** [eclipse/lsp4jakarta#76]
If more than one `@MapKeyJoinColumn` annotation is applied to a field or property, both the `name` and the `referencedColumnName` elements must be specified in each such `@MapKeyJoinColumn` annotation.
https://github.com/eclipse/lsp4jakarta/blob/master/jakarta-eclipse/src/org/jakarta/jdt/persistence/PersistenceMapKeyDiagnosticsCollector.java#L124-L153

Add quick-fix(s) to this diagnostic to add the missing elements to the existing annotations.
See this quick-fix implementation here for modifying an annotation: https://github.com/eclipse/lsp4jakarta/pull/73/files

**Comment by lamminade** [comment]
Ill take a look at this one !
