### ISSUE TITLE
Snippets for new JAX-RS resources

### ISSUE THREAD

**Issue by rzgry** [eclipse/lsp4jakarta#77]
Snippets to quickly create new jax-rs resources / methods.

See an example in lsp4mp: 
https://github.com/eclipse/lsp4mp/blob/master/microprofile.ls/org.eclipse.lsp4mp.ls/src/main/resources/org/eclipse/lsp4mp/snippets/jax-rs.json

Example PR adding snippets for a different spec to the project: https://github.com/eclipse/lsp4jakarta/pull/52/files

**Comment by berasogut** [comment]
Looking into this.
