### ISSUE TITLE
Diagnostic for non-public JAX-RS resource methods. 

### ISSUE THREAD

**Issue by rzgry** [eclipse/lsp4jakarta#78]
From the spec:

"Only public methods may be exposed as resource methods. An implementation SHOULD warn users if a non-public method carries a method designator or `@Path` annotation."

Display a warning on any non-public resource methods that only public methods can be used.

**Comment by MShocrylas** [comment]
Could I work on this issue?

**Comment by kathrynkodama** [comment]
See this class for a similar diagnostic that is delivered on methods of a class: https://github.com/eclipse/lsp4jakarta/blob/master/jakarta-eclipse/src/org/jakarta/jdt/persistence/PersistenceEntityDiagnosticsCollector.java#L161-L165
