### ISSUE TITLE
Jsonb JsonbCreator diagnostic

### ISSUE THREAD

**Issue by kathrynkodama** [eclipse/lsp4jakarta#79]
According to the Jsonb specification: Only one constructor or static factory method can be annotated with JsonbCreator in a given class.
https://jakarta.ee/specifications/jsonb/2.0/apidocs/jakarta/json/bind/annotation/jsonbcreator

Add a diagnostic to ensure that there is only one instance of `@JsonbCreator` in a class and add a corresponding quick fix to remove additional `@JsonbCreator` annotations. 

See [PersistenceEntityDiagnoticsCollector](https://github.com/eclipse/lsp4jakarta/blob/78e6733a9fdc9d7269f571879f5688961f07164c/jakarta-eclipse/src/org/jakarta/jdt/persistence/PersistenceEntityDiagnosticsCollector.java) for similar diagnostics.

**Comment by abhijeetshuklaoist** [comment]
Is this available for me to take? If yes, could you please assign it me? I would like to work on it.

**Comment by kathrynkodama** [comment]
Thanks @abhijeetshuklaoist!

**Comment by mcruzdev** [comment]
@kathrynkodama hello, the next do you can assign to me?

**Comment by abhijeetshuklaoist** [comment]
Sorry @kathrynkodama, I got tied up in other projects, so could not have a look at it. 
@mcruzdev If can fix this quickly, please go ahead as I might not be able to look into it for a while.

**Comment by mcruzdev** [comment]
Hello @kathrynkodama, could you please assign to me?
