### ISSUE TITLE
CDI managed bean with non-public static field and incorrect scope diagnostic

### ISSUE THREAD

**Issue by kathrynkodama** [eclipse/lsp4jakarta#81]
https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#managed_beans
According to the CDI specification: If a managed bean has a non-static public field, it must have scope `@Dependent`. If a managed bean with a non-static public field declares any scope other than `@Dependent`, the container automatically detects the problem and treats it as a definition error.

Deliver a diagnostic warning if the class is annotated with `@ApplicationScoped` (jakarta.enterprise.context.ApplicationScoped), `@ConversationScoped`, `@RequestScoped` or `@SessionScoped` and contains a non-static public field. The diagnostic should be delivered on the non-static public field. 

The following quick-fixes should be available:
- make the field static
- change the scope of the class to `@Dependent`

See javadocs here: https://jakarta.ee/specifications/cdi/2.0/apidocs/

**Comment by kathrynkodama** [comment]
CDI tutorial: https://eclipse-ee4j.github.io/jakartaee-tutorial/cdi-basic.html

**Comment by hanidamlaj** [comment]
Interested in exploring this issue if it's still available! Thank you :)
